export const PARCELS_ENDPOINT = '/parcels'
export const PAYMENTS_ENDPOINT = '/payments/calculate'
export const VALIDATIONS_ENDPOINT = '/actions/validate'
export const APPLICATION_VALIDATIONS_ENDPOINT = '/application/validate'
export const APPLICATION_VALIDATION_RUN_ENDPOINT = '/application/validation-run'
